translation_dict = {
    "@": "at",
    "&": "and",
    "aaa": "apply to affected area",
    "ac": "before meals",
    "ad": "right ear",
    "am": "in the morning",
    "as": "left ear",
    "au": "both ears",
    "bid": "twice daily",
    "bucc": "buccally",
    "c": "capsule",
    "cs": "capsules",
    "d": "daily",
    "gtts": "drop(s)",
    "h": "hours",
    "im": "intramuscularly",
    "inj": "inject",
    "inst": "instill",
    "iv": "intravenously",
    "noct": "at night",
    "nv": "nausea and vomiting",
    "od": "right eye",
    "oes": "on an empty stomach",
    "os": "left eye",
    "ou": "both eyes",
    "p": "pain",
    "pc": "after meals",
    "pm": "in the evening",
    "po": "by mouth",
    "pra": "as needed for anxiety",
    "prf": "as needed for",
    "prn": "as needed",
    "q": "every",
    "qam": "every morning",
    "qd": "every day",
    "qhs": "bedtime",
    "qid": "four times daily",
    "qpm": "every evening",
    "sob": "shortness of breath",
    "sq": "subcutaneously",
    "sub": "sublingually",
    "t": "tablet",
    "tid": "three times daily",
    "tk": "take",
    "ts": "tablets",
    "u": "units",
}
