translation_dict = {
    "tk": "take",
    "inst": "instill",
    "dis": "dissolve",
    "inj": "inject",
    "t": "tablet",
    "c": "capsule",
    "u": "units",
    "ts": "tablets",
    "cs": "capsules",
    "po": "by mouth",
    "bucc": "buccally",
    "sub": "sublingually",
    "iv": "intravenously",
    "im": "intramuscularly",
    "sc": "subcutaneously",
    "qd": "every day",
    "d": "daily",
    "q": "every",
    "bid": "twice daily",
    "tid": "three times daily",
    "qid": "four times daily",
    "h": "hour",
    "hrs": "hours",
    "qam": "every morning",
    "qpm": "every evening",
    "qhs": "at bedtime",
    "hs": "bedtime",
    "prn": "as needed",
    # "prf": "as needed for",
    "pra": "as needed for anxiety",
    "p": "for pain",
    "nv": "nausea and vomiting",
    "sob": "shortness of breath",
    "oes": "on an empty stomach",
    "aaa": "apply to affected area",
    "ac": "before meals",
    "pc": "after meals",
    "cf": "with food",
    "as": "left ear",
    "ad": "right ear",
    "au": "both ears",
    "os": "left eye",
    "od": "right eye",
    "ou": "both eyes",
    "gtt": "drop",
    "gtts": "drops",
    "am": "morning",
    "pm": "evening",
    "apap": "acetaminophen",
    "aud": "use as directed",
    "utd": "as directed",
    "tud": "take as directed",
    "mg": "milligram",
    "g": "gram",
    "kg": "kilogram",
    "ml": "milliliter",
    "gr": "grain",
    "mcg": "microgram",
    "oz": "ounce",
    "bp": "blood pressure",
    "hpb": "high blood pressure",
    "hctz": "hydrochlorothiazide",
    "inh": "inhale",
    "er": "extended release",
    "ir": "immediate release",
    "sr": "sustained release",
    "ec": "enteric coded",
    "iu": "international units",
    "meq": "milliequivalent",
    "nr": "no refills",
    "odt": "orally disintegrating tablet",
    "npo": "nothing by mouth",
    "opht": "ophthalmic",
    "otc": "over the counter",
    "pr": "rectally",
    "pse": "pseudoephedrine",
    "pt": "patient",
    "qdam": "every day in the morning",
    "qdpm": "every day in the evening",
    "qh": "every hour",
    "q12h": "every 12 hours",
    "q6h": "every 6 hours",
    "q4h": "every 4 hours",
    "q8h": "every 8 hours",
    "q24h": "every 24 hours",
    "q4-6h": "every 4 to 6 hours",
    "q2-3h": "every 2 to 3 hours",
    "q2-4h": "every 2 to 4 hours",
    "qod": "every other day",
    "qw": "weekly",
    "tiw": "three times a week",
    "tsp": "teaspoonful",
    "tbsp": "tablespoonful",
    "tat": "unitl all taken",
    "uad": "use as directed",
    "ung": "ointment",
    "cre": "cream",
    "susp": "suspension",
    "elix": "elixir",
    "syrp": "syrup",
    "syr": "syringe",
    "ss": "one half",
    "stat": "immediately",
    "supp": "suppository",
    "vag": "vaginally",
    "w/": "with",
    "w/o": "without",
    "wk": "week",
}
